### PR TITLE
Add data attribute so that subject in planner preview can be found

### PR DESCRIPTION
**Pull request by mwilliamson-firefly**

### CODE REVIEW

**Comment by roobottom** [comment]
@mwilliamson-firefly can this go into `feature-planner` please?

**Comment by mwilliamson-firefly** [comment]
It certainly can.

**Comment by mwilliamson-firefly** [comment]
@roobottom Where is the planner preview XSL in that branch?

**Comment by roobottom** [comment]
@mwilliamson-firefly d'oh! Sorry, planner-preview is in the `feature-dashboard` branch.

**Comment by mwilliamson-firefly** [comment]
Not to worry, should be a new pull request against that branch now.

**Pull request closed without merging**
