### PR TITLE
Planner: Go to current date in date picker

### PR DESCRIPTION
**Pull request by mwilliamson-firefly**

### CODE REVIEW

**Comment by mwilliamson-firefly** [comment]
This includes the change in #54, so that should be merged into `common`, then `common` merged into `feature-planner` before this gets merged.

**Comment by roobottom** [comment]
@mwilliamson-firefly Can you make this PR to  `common` please — we moved this block. Sorry, very confusing I know.

**Comment by mwilliamson-firefly** [comment]
@roobottom As in move the changes in `ff_module-planner-date-picker-jumpto` to `common`? I can't see that module in there.

**Comment by roobottom** [comment]
@mwilliamson-firefly Ignore me. There are several modules for this now all with _very_ similar names.

**Pull request merged**
