### PR TITLE
Increase hit area of columnar list item

### PR DESCRIPTION
**Pull request by boonier**
Adds an extra span wrapper around content to control the spacing consistently for both Links and Non-links.

Also corrected the md file - 'two-column' modifier was spelt incorrectly.

### CODE REVIEW

**Comment by aegirfirefly** [comment]
The Melody fix looks fine, can you do the same for Folio and Nautilus - or in core?

**Comment by boonier** [comment]
Hmm yes it does seem like a similar scenario that might be best place in the core style. @dkhuntrods any objections?

**Comment by dkhuntrods** [comment]
@aegirfirefly @boonier I can't help but feel that in this case it would be preferable not to have to have the span - if the link is inline-block, does the padding apply to both that and the text content?
It just seems like there should be a simpler way to do that...

**Comment by boonier** [comment]
The reason for that span is if there is no link `<a>` on the list item, then there is no hook to style it with, and the padding needs to reside within the `<a>` not the parent `<li>` to increase the hit area. If only the links have the vertical padding then spacing of the items goes out of wack.

If it is unlikely that the contents of a columnar-list is going to be anything but a link, then we could dispense of the span, sure.

**Comment by dkhuntrods** [comment]
What about __item > \* {} for a hook?

**Comment by boonier** [comment]
Have updated the PR that removes the dependancy on span markup. The above __item > \* {} would only  affect a child afaik (unless I'm missing something), and the list item without url just contains the raw text content; no child node. So I've gone down the modifier route and it's working well.

**Comment by aegirfirefly** [comment]
Cool. Could we have it so that a span only gets added if there's no link? I assume we'll have columnar lists in variable non-linky places.

**Comment by boonier** [comment]
What I've done doesn't need the span tag and is only dependant on the class modifier. `ff_module-columnar-list--no-url` is only added if there is no presence of a url in the xml.

**Comment by dkhuntrods** [comment]
Ok...think that's a bit cleaner; I'd probably invert the check myself as you're already checking for a url and could just hook into that (so the class would only be added if url present, and class would be `--with-url` or something). To my mind, the li is the standard case, and having a url is an addition or modifier.

**Comment by boonier** [comment]
@dkhuntrods cool good point

Re the original question, should this be part of the core styles?

**Comment by boonier** [comment]
Updated. Should I remove the empty theme specific files (melody, nautilus, folio)?

**Comment by dkhuntrods** [comment]
LGTM, if @aegirfirefly's happy too :)

**Pull request merged**
