### PR TITLE
Build of Folio for Epic 1 components only

### PR DESCRIPTION
**Pull request by aegirfirefly**
Dashboard section, landing section and headings/links - visible in FF5 with FF6 nav.

Also has settings and colours from Folio - the rest of the patterns currently apply these wrong, so please ignore.

### CODE REVIEW

**Comment by dkhuntrods** [comment]
All I can see are icon file changes, is that right?

**Comment by aegirfirefly** [comment]
No, there are changes to the containers listed in the PR message. The icons are just from copying them over.

**Comment by dkhuntrods** [comment]
Would those be .xsl files? I can't see them in the diff :<

**Comment by aegirfirefly** [comment]
They are there, right after all the icons. Github complains it can't show the whole diff because too many files have changed.

**Comment by dkhuntrods** [comment]
Ok, even after checking out I'm still not seeing any .xsl files!

**Comment by dkhuntrods** [comment]
Right, can't leave comments inline - 

```
    &__main {
        #ff_mix-sections > .main();
        padding: 0 @ff_size_control_horizontal;
    }
```

Since that padding is added in both sections, would it make sense to add it into `#ff_mix-sections > .main();`?

Otherwise, LGTM

**Comment by aegirfirefly** [comment]
@dkhuntrods I can't be sure until later - if I find myself adding it to other places where it's used I'll add it to the mixin.

**Pull request merged**
